### ISSUE TITLE
Update OpenCV version to 4.5.0

### ISSUE THREAD

**Issue by Husseinhj** [WebsiteBeaver/android-document-scanner#13]
When will you be updated from v4.1.0 to v4.5.5 of OpenCV?

This version has a smaller application size, and upgrading to this version would be great.

**Comment by dmarcs** [comment]
An older version was using 4.5.5, but I downgraded to 4.1.0 because 4.5.5 didn't work with React Native. 

4.1.0 has libc built in, and 4.5.5 has libc as an external dependency. React Native also uses libc, but a different version than OpenCV.

The best option is to compile OpenCV, and only use parts of the library that we need instead of using the entire OpenCV library. I might do that in the future.
